version: '3'

services:
    nginx:
        container_name: deploy-stickers-nginx
        build:
            context: ./containers/nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./releases:/releases
        depends_on:
            - php
        networks:
            - stickers_deploy

    php:
        container_name: deploy-stickers-php
        build:
            context: ./containers/php
        volumes:
            - ./containers/php/php.ini:/etc/php.d/php.ini
            - ./releases:/releases
            - ./ssh/authorized_keys:/root/.ssh/authorized_keys
            - ./scripts:/scripts
        networks:
            - stickers_deploy

    ssh:
        container_name: deploy-stickers-ssh
        build:
            context: ./containers/ssh
        volumes:
            - ./releases:/releases
            - ./webroot:/var/www
            - ./ssh/authorized_keys:/root/.ssh/authorized_keys
            - ./scripts:/scripts
        ports:
            - "2222:22"
        networks:
            - stickers_deploy
    mysql:
        image: mariadb:10.1.43
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: stickers
        volumes:
            - ./mysql_data:/var/lib/mysql
        networks:
            - stickers_deploy

networks:
    stickers_deploy:
        external:
            name: stickers_deploy
