#!/bin/bash

release_name=$(date +%Y%m%d%H%M%S)_frontend
release_path=/releases/"$release_name"
cd /releases
mkdir "$release_name"
chown -R 1000:1000 ./"$release_name"
mv /archives/frontend.tar "$release_path"
cd "$release_path"
tar -xf frontend.tar ./
chown -R apache:apache ./*
rm frontend.tar
cd /releases
unlink current_frontend
ln -s "$release_path" current_frontend
chown 1000:1000 current_frontend
cd /scripts
php clear_old_releases.php